/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DRIVE_PB_H_INCLUDED
#define PB_DRIVE_PB_H_INCLUDED
#include "utils/pb.h"
#include "status.pb.h"
#include "utils.pb.h"
#include "version.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _DriveMotor {
    DriveMotor_FRONT_LEFT = 0,
    DriveMotor_FRONT_RIGHT = 1,
    DriveMotor_MIDDLE_LEFT = 3,
    DriveMotor_MIDDLE_RIGHT = 4,
    DriveMotor_BACK_LEFT = 5,
    DriveMotor_BACK_RIGHT = 6
} DriveMotor;

typedef enum _ProtoColor {
    ProtoColor_PROTO_COLOR_UNDEFINED = 0,
    ProtoColor_RED = 1,
    ProtoColor_GREEN = 2,
    ProtoColor_BLUE = 3,
    ProtoColor_UNLIT = 4
} ProtoColor;

typedef enum _MotorErrorCode {
    MotorErrorCode_NO_FAULT = 0,
    MotorErrorCode_OVER_TEMP = 1,
    MotorErrorCode_OVER_CURRENT = 2,
    MotorErrorCode_OVER_VOLTAGE = 3,
    MotorErrorCode_UNDER_VOLTAGE = 4,
    MotorErrorCode_ENCODER_FAULT = 5,
    MotorErrorCode_MOSFET_OVER_TEMP = 6,
    MotorErrorCode_UNKNOWN_ERROR = 7
} MotorErrorCode;

/* Struct definitions */
typedef struct _DriveCommand {
    /* The max speed, as a percentage of the rover's possible speed. */
    float throttle;
    /* Speed of the left wheels, as a percentage of [throttle]. */
    float left;
    /* Speed of the right wheels, as a percentage of [throttle]. */
    float right;
    /* Indicates that [left] = 0 is valid, even though 0 usually means no value. */
    bool set_left;
    /* Indicates that [right] = 0 is valid, even though 0 usually means no value. */
    bool set_right;
    /* Indicates that [throttle] = 0 is valid, even though 0 usually means no value. */
    bool set_throttle;
    float front_swivel;
    float front_tilt;
    float rear_swivel;
    float rear_tilt;
    RoverStatus status;
    bool has_version;
    Version version;
    ProtoColor color;
    BoolState blink;
} DriveCommand;

typedef struct _DriveMotorData {
    float speed;
    float current;
    int32_t temperature;
    MotorErrorCode error;
} DriveMotorData;

typedef struct _DriveData {
    /* The max speed, as a percentage of the rover's possible speed. */
    float throttle;
    /* Speed of the left wheels, as a percentage of [throttle]. */
    float left;
    /* Speed of the right wheels, as a percentage of [throttle]. */
    float right;
    /* Indicates that [left] = 0 is valid, even though 0 usually means no value. */
    bool set_left;
    /* Indicates that [right] = 0 is valid, even though 0 usually means no value. */
    bool set_right;
    /* Indicates that [throttle] = 0 is valid, even though 0 usually means no value. */
    bool set_throttle;
    float front_swivel;
    float front_tilt;
    float rear_swivel;
    float rear_tilt;
    /* Vitals for the whole rover */
    float battery_voltage;
    float battery_current;
    float battery_temperature;
    bool has_version;
    Version version;
    ProtoColor color;
    RoverStatus status;
    /* Contains the DriveMotorData for each corresponding motor */
    bool has_front_left_motor;
    DriveMotorData front_left_motor;
    bool has_middle_left_motor;
    DriveMotorData middle_left_motor;
    bool has_back_left_motor;
    DriveMotorData back_left_motor;
    bool has_front_right_motor;
    DriveMotorData front_right_motor;
    bool has_middle_right_motor;
    DriveMotorData middle_right_motor;
    bool has_back_right_motor;
    DriveMotorData back_right_motor;
} DriveData;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _DriveMotor_MIN DriveMotor_FRONT_LEFT
#define _DriveMotor_MAX DriveMotor_BACK_RIGHT
#define _DriveMotor_ARRAYSIZE ((DriveMotor)(DriveMotor_BACK_RIGHT+1))

#define _ProtoColor_MIN ProtoColor_PROTO_COLOR_UNDEFINED
#define _ProtoColor_MAX ProtoColor_UNLIT
#define _ProtoColor_ARRAYSIZE ((ProtoColor)(ProtoColor_UNLIT+1))

#define _MotorErrorCode_MIN MotorErrorCode_NO_FAULT
#define _MotorErrorCode_MAX MotorErrorCode_UNKNOWN_ERROR
#define _MotorErrorCode_ARRAYSIZE ((MotorErrorCode)(MotorErrorCode_UNKNOWN_ERROR+1))

#define DriveCommand_status_ENUMTYPE RoverStatus
#define DriveCommand_color_ENUMTYPE ProtoColor
#define DriveCommand_blink_ENUMTYPE BoolState

#define DriveMotorData_error_ENUMTYPE MotorErrorCode

#define DriveData_color_ENUMTYPE ProtoColor
#define DriveData_status_ENUMTYPE RoverStatus


/* Initializer values for message structs */
#define DriveCommand_init_default                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _RoverStatus_MIN, false, Version_init_default, _ProtoColor_MIN, _BoolState_MIN}
#define DriveMotorData_init_default              {0, 0, 0, _MotorErrorCode_MIN}
#define DriveData_init_default                   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, Version_init_default, _ProtoColor_MIN, _RoverStatus_MIN, false, DriveMotorData_init_default, false, DriveMotorData_init_default, false, DriveMotorData_init_default, false, DriveMotorData_init_default, false, DriveMotorData_init_default, false, DriveMotorData_init_default}
#define DriveCommand_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _RoverStatus_MIN, false, Version_init_zero, _ProtoColor_MIN, _BoolState_MIN}
#define DriveMotorData_init_zero                 {0, 0, 0, _MotorErrorCode_MIN}
#define DriveData_init_zero                      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, false, Version_init_zero, _ProtoColor_MIN, _RoverStatus_MIN, false, DriveMotorData_init_zero, false, DriveMotorData_init_zero, false, DriveMotorData_init_zero, false, DriveMotorData_init_zero, false, DriveMotorData_init_zero, false, DriveMotorData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define DriveCommand_throttle_tag                1
#define DriveCommand_left_tag                    2
#define DriveCommand_right_tag                   3
#define DriveCommand_set_left_tag                4
#define DriveCommand_set_right_tag               5
#define DriveCommand_set_throttle_tag            6
#define DriveCommand_front_swivel_tag            7
#define DriveCommand_front_tilt_tag              8
#define DriveCommand_rear_swivel_tag             9
#define DriveCommand_rear_tilt_tag               10
#define DriveCommand_status_tag                  11
#define DriveCommand_version_tag                 12
#define DriveCommand_color_tag                   13
#define DriveCommand_blink_tag                   14
#define DriveMotorData_speed_tag                 1
#define DriveMotorData_current_tag               2
#define DriveMotorData_temperature_tag           3
#define DriveMotorData_error_tag                 4
#define DriveData_throttle_tag                   1
#define DriveData_left_tag                       2
#define DriveData_right_tag                      3
#define DriveData_set_left_tag                   4
#define DriveData_set_right_tag                  5
#define DriveData_set_throttle_tag               6
#define DriveData_front_swivel_tag               7
#define DriveData_front_tilt_tag                 8
#define DriveData_rear_swivel_tag                9
#define DriveData_rear_tilt_tag                  10
#define DriveData_battery_voltage_tag            11
#define DriveData_battery_current_tag            12
#define DriveData_battery_temperature_tag        13
#define DriveData_version_tag                    14
#define DriveData_color_tag                      21
#define DriveData_status_tag                     22
#define DriveData_front_left_motor_tag           23
#define DriveData_middle_left_motor_tag          24
#define DriveData_back_left_motor_tag            25
#define DriveData_front_right_motor_tag          26
#define DriveData_middle_right_motor_tag         27
#define DriveData_back_right_motor_tag           28

/* Struct field encoding specification for nanopb */
#define DriveCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    throttle,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    left,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    right,             3) \
X(a, STATIC,   SINGULAR, BOOL,     set_left,          4) \
X(a, STATIC,   SINGULAR, BOOL,     set_right,         5) \
X(a, STATIC,   SINGULAR, BOOL,     set_throttle,      6) \
X(a, STATIC,   SINGULAR, FLOAT,    front_swivel,      7) \
X(a, STATIC,   SINGULAR, FLOAT,    front_tilt,        8) \
X(a, STATIC,   SINGULAR, FLOAT,    rear_swivel,       9) \
X(a, STATIC,   SINGULAR, FLOAT,    rear_tilt,        10) \
X(a, STATIC,   SINGULAR, UENUM,    status,           11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,          12) \
X(a, STATIC,   SINGULAR, UENUM,    color,            13) \
X(a, STATIC,   SINGULAR, UENUM,    blink,            14)
#define DriveCommand_CALLBACK NULL
#define DriveCommand_DEFAULT NULL
#define DriveCommand_version_MSGTYPE Version

#define DriveMotorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    current,           2) \
X(a, STATIC,   SINGULAR, INT32,    temperature,       3) \
X(a, STATIC,   SINGULAR, UENUM,    error,             4)
#define DriveMotorData_CALLBACK NULL
#define DriveMotorData_DEFAULT NULL

#define DriveData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    throttle,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    left,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    right,             3) \
X(a, STATIC,   SINGULAR, BOOL,     set_left,          4) \
X(a, STATIC,   SINGULAR, BOOL,     set_right,         5) \
X(a, STATIC,   SINGULAR, BOOL,     set_throttle,      6) \
X(a, STATIC,   SINGULAR, FLOAT,    front_swivel,      7) \
X(a, STATIC,   SINGULAR, FLOAT,    front_tilt,        8) \
X(a, STATIC,   SINGULAR, FLOAT,    rear_swivel,       9) \
X(a, STATIC,   SINGULAR, FLOAT,    rear_tilt,        10) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_voltage,  11) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_current,  12) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_temperature,  13) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,          14) \
X(a, STATIC,   SINGULAR, UENUM,    color,            21) \
X(a, STATIC,   SINGULAR, UENUM,    status,           22) \
X(a, STATIC,   OPTIONAL, MESSAGE,  front_left_motor,  23) \
X(a, STATIC,   OPTIONAL, MESSAGE,  middle_left_motor,  24) \
X(a, STATIC,   OPTIONAL, MESSAGE,  back_left_motor,  25) \
X(a, STATIC,   OPTIONAL, MESSAGE,  front_right_motor,  26) \
X(a, STATIC,   OPTIONAL, MESSAGE,  middle_right_motor,  27) \
X(a, STATIC,   OPTIONAL, MESSAGE,  back_right_motor,  28)
#define DriveData_CALLBACK NULL
#define DriveData_DEFAULT NULL
#define DriveData_version_MSGTYPE Version
#define DriveData_front_left_motor_MSGTYPE DriveMotorData
#define DriveData_middle_left_motor_MSGTYPE DriveMotorData
#define DriveData_back_left_motor_MSGTYPE DriveMotorData
#define DriveData_front_right_motor_MSGTYPE DriveMotorData
#define DriveData_middle_right_motor_MSGTYPE DriveMotorData
#define DriveData_back_right_motor_MSGTYPE DriveMotorData

extern const pb_msgdesc_t DriveCommand_msg;
extern const pb_msgdesc_t DriveMotorData_msg;
extern const pb_msgdesc_t DriveData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DriveCommand_fields &DriveCommand_msg
#define DriveMotorData_fields &DriveMotorData_msg
#define DriveData_fields &DriveData_msg

/* Maximum encoded size of messages (where known) */
#define DRIVE_PB_H_MAX_SIZE                      DriveData_size
#define DriveCommand_size                        71
#define DriveData_size                           242
#define DriveMotorData_size                      23

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
